[{
"category": "clap",
"sounds": [{"name": "a_clap_1", "soundtype": "sound", "url": "/public/wav/clap/a_clap_1.wav"},{"name": "b_clap_1", "soundtype": "sound", "url": "/public/wav/clap/b_clap_1.wav"},{"name": "b_clap_2", "soundtype": "sound", "url": "/public/wav/clap/b_clap_2.wav"},{"name": "c_clap_1", "soundtype": "sound", "url": "/public/wav/clap/c_clap_1.wav"},{"name": "d_clap_1", "soundtype": "sound", "url": "/public/wav/clap/d_clap_1.wav"},{"name": "d_clap_2", "soundtype": "sound", "url": "/public/wav/clap/d_clap_2.wav"},{"name": "e_clap_1", "soundtype": "sound", "url": "/public/wav/clap/e_clap_1.wav"},{"name": "f_clap_1", "soundtype": "sound", "url": "/public/wav/clap/f_clap_1.wav"},{"name": "f_sharp__clap_1", "soundtype": "sound", "url": "/public/wav/clap/f_sharp__clap_1.wav"},{"name": "f_sharp__clap_2", "soundtype": "sound", "url": "/public/wav/clap/f_sharp__clap_2.wav"},{"name": "g_clap_1", "soundtype": "sound", "url": "/public/wav/clap/g_clap_1.wav"},{"name": "g_clap_2", "soundtype": "sound", "url": "/public/wav/clap/g_clap_2.wav"},{"name": "g_sharp__clap_1", "soundtype": "sound", "url": "/public/wav/clap/g_sharp__clap_1.wav"},{"name": "g_sharp__clap_2", "soundtype": "sound", "url": "/public/wav/clap/g_sharp__clap_2.wav"},{"name": "g_sharp__clap_3", "soundtype": "sound", "url": "/public/wav/clap/g_sharp__clap_3.wav"}]
},
{
"category": "hat",
"sounds": [{"name": "a_hat_1", "soundtype": "sound", "url": "/public/wav/hat/a_hat_1.wav"},{"name": "a_hat_2", "soundtype": "sound", "url": "/public/wav/hat/a_hat_2.wav"},{"name": "b_hat_1", "soundtype": "sound", "url": "/public/wav/hat/b_hat_1.wav"},{"name": "b_hat_2", "soundtype": "sound", "url": "/public/wav/hat/b_hat_2.wav"},{"name": "c_hat_1", "soundtype": "sound", "url": "/public/wav/hat/c_hat_1.wav"},{"name": "c_hat_2", "soundtype": "sound", "url": "/public/wav/hat/c_hat_2.wav"},{"name": "c_hat_3", "soundtype": "sound", "url": "/public/wav/hat/c_hat_3.wav"},{"name": "d_hat_1", "soundtype": "sound", "url": "/public/wav/hat/d_hat_1.wav"},{"name": "d_hat_2", "soundtype": "sound", "url": "/public/wav/hat/d_hat_2.wav"},{"name": "d_hat_3", "soundtype": "sound", "url": "/public/wav/hat/d_hat_3.wav"},{"name": "f_sharp__hat_1", "soundtype": "sound", "url": "/public/wav/hat/f_sharp__hat_1.wav"},{"name": "g_hat_1", "soundtype": "sound", "url": "/public/wav/hat/g_hat_1.wav"},{"name": "g_hat_2", "soundtype": "sound", "url": "/public/wav/hat/g_hat_2.wav"},{"name": "g_hat_3", "soundtype": "sound", "url": "/public/wav/hat/g_hat_3.wav"},{"name": "g_hat_9", "soundtype": "sound", "url": "/public/wav/hat/g_hat_9.wav"}]
},
{
"category": "kick",
"sounds": [{"name": "a_kick_01", "soundtype": "sound", "url": "/public/wav/kick/a_kick_01.wav"},{"name": "a_kick_02", "soundtype": "sound", "url": "/public/wav/kick/a_kick_02.wav"},{"name": "a_kick_03", "soundtype": "sound", "url": "/public/wav/kick/a_kick_03.wav"},{"name": "b_kick_01", "soundtype": "sound", "url": "/public/wav/kick/b_kick_01.wav"},{"name": "b_kick_02", "soundtype": "sound", "url": "/public/wav/kick/b_kick_02.wav"},{"name": "c_kick_01", "soundtype": "sound", "url": "/public/wav/kick/c_kick_01.wav"},{"name": "c_kick_02", "soundtype": "sound", "url": "/public/wav/kick/c_kick_02.wav"},{"name": "c_kick_03", "soundtype": "sound", "url": "/public/wav/kick/c_kick_03.wav"},{"name": "d_kick_01", "soundtype": "sound", "url": "/public/wav/kick/d_kick_01.wav"},{"name": "d_kick_02", "soundtype": "sound", "url": "/public/wav/kick/d_kick_02.wav"},{"name": "e_kick_01", "soundtype": "sound", "url": "/public/wav/kick/e_kick_01.wav"},{"name": "e_kick_02", "soundtype": "sound", "url": "/public/wav/kick/e_kick_02.wav"},{"name": "e_kick_03", "soundtype": "sound", "url": "/public/wav/kick/e_kick_03.wav"},{"name": "f_kick_01", "soundtype": "sound", "url": "/public/wav/kick/f_kick_01.wav"},{"name": "f_sharp__kick_01", "soundtype": "sound", "url": "/public/wav/kick/f_sharp__kick_01.wav"}]
},
{
"category": "snare",
"sounds": [{"name": "a_sharp__snare_1", "soundtype": "sound", "url": "/public/wav/snare/a_sharp__snare_1.wav"},{"name": "b_snare_1", "soundtype": "sound", "url": "/public/wav/snare/b_snare_1.wav"},{"name": "b_snare_2", "soundtype": "sound", "url": "/public/wav/snare/b_snare_2.wav"},{"name": "b_snare_3", "soundtype": "sound", "url": "/public/wav/snare/b_snare_3.wav"},{"name": "c_sharp__snare_01", "soundtype": "sound", "url": "/public/wav/snare/c_sharp__snare_01.wav"},{"name": "c_sharp__snare_1", "soundtype": "sound", "url": "/public/wav/snare/c_sharp__snare_1.wav"},{"name": "d_snare_01", "soundtype": "sound", "url": "/public/wav/snare/d_snare_01.wav"},{"name": "d_snare_1", "soundtype": "sound", "url": "/public/wav/snare/d_snare_1.wav"},{"name": "e_snare_01", "soundtype": "sound", "url": "/public/wav/snare/e_snare_01.wav"},{"name": "e_snare_02", "soundtype": "sound", "url": "/public/wav/snare/e_snare_02.wav"},{"name": "e_snare_03", "soundtype": "sound", "url": "/public/wav/snare/e_snare_03.wav"},{"name": "f_sharp__snare_1", "soundtype": "sound", "url": "/public/wav/snare/f_sharp__snare_1.wav"},{"name": "f_sharp__snare_2", "soundtype": "sound", "url": "/public/wav/snare/f_sharp__snare_2.wav"},{"name": "g_snare_1", "soundtype": "sound", "url": "/public/wav/snare/g_snare_1.wav"},{"name": "g_snare_2", "soundtype": "sound", "url": "/public/wav/snare/g_snare_2.wav"}]
},
{
"category": "tom",
"sounds": [{"name": "a_tom_01", "soundtype": "sound", "url": "/public/wav/tom/a_tom_01.wav"},{"name": "a_tom_1", "soundtype": "sound", "url": "/public/wav/tom/a_tom_1.wav"},{"name": "c_sharp__tom_1", "soundtype": "sound", "url": "/public/wav/tom/c_sharp__tom_1.wav"},{"name": "c_tom_1", "soundtype": "sound", "url": "/public/wav/tom/c_tom_1.wav"},{"name": "c_tom_2", "soundtype": "sound", "url": "/public/wav/tom/c_tom_2.wav"},{"name": "c_tom_3", "soundtype": "sound", "url": "/public/wav/tom/c_tom_3.wav"},{"name": "d_sharp__tom_1", "soundtype": "sound", "url": "/public/wav/tom/d_sharp__tom_1.wav"},{"name": "d_sharp__tom_2", "soundtype": "sound", "url": "/public/wav/tom/d_sharp__tom_2.wav"},{"name": "e_tom_1", "soundtype": "sound", "url": "/public/wav/tom/e_tom_1.wav"},{"name": "e_tom_2", "soundtype": "sound", "url": "/public/wav/tom/e_tom_2.wav"},{"name": "e_tom_3", "soundtype": "sound", "url": "/public/wav/tom/e_tom_3.wav"},{"name": "f_sharp__tom_1", "soundtype": "sound", "url": "/public/wav/tom/f_sharp__tom_1.wav"},{"name": "g_sharp__tom_1", "soundtype": "sound", "url": "/public/wav/tom/g_sharp__tom_1.wav"},{"name": "g_sharp__tom_2", "soundtype": "sound", "url": "/public/wav/tom/g_sharp__tom_2.wav"},{"name": "g_tom_1", "soundtype": "sound", "url": "/public/wav/tom/g_tom_1.wav"}]
},
{
"category": "impulses",
"sounds": [{"name": "five columns", "soundtype": "impulse", "url": "/public/wav/impulses/five columns.wav"},{"name": "five_columns_long", "soundtype": "impulse", "url": "/public/wav/impulses/five_columns_long.wav"},{"name": "french 18th century salon", "soundtype": "impulse", "url": "/public/wav/impulses/french 18th century salon.wav"},{"name": "going home", "soundtype": "impulse", "url": "/public/wav/impulses/going home.wav"},{"name": "in the silo revised", "soundtype": "impulse", "url": "/public/wav/impulses/in the silo revised.wav"},{"name": "narrow bumpy space", "soundtype": "impulse", "url": "/public/wav/impulses/narrow bumpy space.wav"},{"name": "nice drum room", "soundtype": "impulse", "url": "/public/wav/impulses/nice drum room.wav"},{"name": "parking garage", "soundtype": "impulse", "url": "/public/wav/impulses/parking garage.wav"},{"name": "rays", "soundtype": "impulse", "url": "/public/wav/impulses/rays.wav"},{"name": "trig room", "soundtype": "impulse", "url": "/public/wav/impulses/trig room.wav"}]
}]
